*** Settings ***
Documentation  This file contains car data keys variables.

*** Variables ***
${BODY_TYPE_KEY}              bodyType
${BUYING_CAR_KEY}             buyingCar
${ENGINE_KEY}                 engine
${ENGINE_POWER_KEY}           enginePower
${FIRSTR_EGISTERED_KEY}       firstRegistered
${FUEL_TYPE_KEY}              fuelType
${INCEPTION_DATE_OFFSET_KEY}  inceptionDateOffset
${IS_CAR_NEW_KEY}             isCarNew
${MAKE_KEY}                   make
${MODEL_KEY}                  model
${OWNER_EGISTERED_KEY}        ownerRegistered
${REGISTERED_OWNER_KEY}       registeredOwner